name: continuous deployment test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: ssh deploy
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile.pem
          chmod 600 keyfile.pem
          mkdir -p ~/.ssh
          ssh-keyscan ec2-3-92-207-202.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          ssh -t -i keyfile.pem ubuntu@3.92.207.202 "sudo bash ~/deplot.sh"
